# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91854ca95d284ef2eee4e46a2515e3c633d738ef70a5a850a272a13ceff440ca88354e16e1141519d8d543c9fa59cb3524ef5345bcb424a6b6894f3127662c15

test:
  secret_key_base: 1962e10e71d5aba6517a0a8d05a6da9ce875661c569ecee11452b568b863a7e7b6dc26d9732ff7089a22d79857e903b697460b3e842c2db69f99039f14119dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
